### ISSUE TITLE
Sorting of versions in deployment modal

### ISSUE THREAD

**Issue by cokert** [turnerlabs/udeploy#12]
Hey, guys.  I work on the ODT/Compass team with Bart Alcorn/Cea Mosley.  Would it be possible to sort the versions in the deployment modal by the task definition revision number instead of the version #/maybe have this as a configuration option?  The go code is returning a map instead of an array, so it'd be a bit more involved than just sorting an array differently somewhere.  

I don't mind doing the changes and submitting a PR, but it's non-trivial to get an instance running to experiment with.  I may try again tonight/tomorrow, but I have an @turner address and am on slack if any of you have a few minutes to give me a hand setting it up locally.

**Comment by kendavis2** [comment]
@cokert udeploy rolls task definition revision numbers up into a single version; so, a single version only shows the latest task def revision that applies to that version. If you sort by task def revision, you still would not see all of them in the event they were rolled up. I am curious what use case you are trying to solve for? Does your team use the task def revision number instead of the version?

I would be glad to help you get it setup locally to do development. I will reach out to you and we can work from there.

**Comment by cokert** [comment]
After talking things through today, we don't really need this, so I'm closing this issue.
